# Generated by Django 5.0.3 on 2024-03-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author',
            new_name='authorname',
        ),
    ]
